### ISSUE TITLE
mux2pin15

### ISSUE THREAD

**Issue by ragekillen** [ristoinnovates/ultimate-midi-controller#1]
Is the rotary encoder with button supposed to be mux1pin15 or is it supposed to go to pin 15 on the cd4051be chip (muxSig1). pretty sure its just a typo in the schematic

**Comment by ristoinnovates** [comment]
You are correct! Good catch! It's supposed to be mux1Pin15.

I counted the 4067s as one and two, and the 4051s as one and two as well when making the schematic. 

Thank you for checking it. I'll update it when I get a chance! Send me an email at ristoinnovates@gmail.com, I'll send you a 15% OFF coupon code if you ever want to get a device from my website.

Thanks!

**Comment by ragekillen** [comment]
thanks for confirming that. As for the coupon i appreciate the offer but no need i would rather support you by paying the full amount
